# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxSJPageViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxSJPageViewController
  pod 'RxSwift'
  pod 'RxDataSources'
  pod 'SJPageViewController/ObjC'

  target 'RxSJPageViewControllerTests' do
    # Pods for testing
  end

end
